name: Pipeline de Teste

on:
  push:
    branches:
      - main

# permissions:
#   contents: read
#   packages: write

jobs:
  tests:
    name: Roda o Pytest
    runs-on: ubuntu-latest
    container: python:3.11-slim
    steps:
      - uses: actions/checkout@v3
      - run: pip install pytest
      - run: pytest .

  build:
    name: Executa um processo de build
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{secrets.GITHUB_TOKEN}}" | docker login ghrc.io -u ${{ github.actor }} --password-stdin
      - run: docker build -t "ghcr.io/lukerops/ufes-aula-pipeline:latest" -f Dockerfile .
      - run: docker images
      - run: docker push "ghcr.io/lukerops/ufes-aula-pipeline:latest"
